<?php


namespace YiluTech\YiMQ\Subtask;


use YiluTech\YiMQ\Constants\ProcessStatus;
use YiluTech\YiMQ\Constants\SubtaskType;
use YiluTech\YiMQ\Models\Subtask as SubtaskModel;
use YiluTech\YiMQ\Subtask\BaseSubtask\BaseTccSubtask;
use YiluTech\YiMQ\Subtask\BaseSubtask\ProcessorSubtask;

class TccSubtask extends BaseTccSubtask
{
    public $serverType = 'TCC';
    public $type = SubtaskType::TCC;

    public function try()
    {
        return parent::_try(); // TODO: Change the autogenerated stub
    }
}