<?php


namespace YiluTech\YiMQ\Subtask;


use YiluTech\YiMQ\Constants\SubtaskType;
use YiluTech\YiMQ\Subtask\BaseSubtask\BaseTccSubtask;

class XaSubtask extends BaseTccSubtask
{
    public $serverType = 'XA';
    public $type = SubtaskType::XA;

    public function prepare()
    {
        return parent::_try(); // TODO: Change the autogenerated stub
    }


}